
services:
  backend:
    container_name: assets_backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    command: sh -c 'npx serverless offline --host 0.0.0.0'

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - 5173
    ports:
      - 5173:5173
    command: sh -c 'npm run dev'
    
    
